name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 4.5.0.16
  BLOCKY_VERSION: 0.23

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl
      id: build_armv7hl
      run: docker run --rm --privileged -v $PWD:/workspace coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            cd rpm ;
            curl -OL https://github.com/0xERR0R/blocky/releases/download/v${BLOCKY_VERSION}/blocky_v${BLOCKY_VERSION}_Linux_armv7.tar.gz ;
            cd .. ;
            mb2 -t SailfishOS-$RELEASE-armv7hl build --prepare ;
            sudo mkdir -p /workspace/RPMS ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Build aarch64
      id: build_aarch64
      run: docker run --rm --privileged -v $PWD:/workspace coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            cd rpm ;
            curl -OL https://github.com/0xERR0R/blocky/releases/download/v${BLOCKY_VERSION}/blocky_v${BLOCKY_VERSION}_Linux_arm64.tar.gz ;
            cd .. ;
            mb2 -t SailfishOS-$RELEASE-aarch64 build --prepare ;
            sudo mkdir -p /workspace/RPMS ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

